apiVersion: v1
kind: Service
metadata:
  name: {{ include "eshop.fullname" . }}-frontend
  namespace: {{ include "eshop.fullname" . }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "eshop.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend 