{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eshop.fullname" . }}-redis
  namespace: {{ include "eshop.fullname" . }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "eshop.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }} 