apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eshop.fullname" . }}-secrets
  namespace: {{ include "eshop.fullname" . }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  jwt-secret: {{ .Values.backend.env.JWT_SECRET | b64enc | quote }}
  db-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  {{- if .Values.backend.env.SENTRY_DSN }}
  sentry-dsn: {{ .Values.backend.env.SENTRY_DSN | b64enc | quote }}
  {{- end }} 