# Default values for eshop Helm chart

# Global settings
global:
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

# Backend configuration
backend:
  image:
    repository: yourrepo/eshop-backend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001
  env:
    NODE_ENV: production
    PORT: 3001
    JWT_SECRET: changeme
    DB_HOST: eshop-postgres
    DB_PORT: 5432
    DB_NAME: eshop
    DB_USER: eshop
    DB_PASSWORD: eshop_password
    REDIS_HOST: eshop-redis
    REDIS_PORT: 6379
    REDIS_PASSWORD: eshop_redis_password
    FRONTEND_URL: http://eshop-frontend:3000
    SENTRY_DSN: ""
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  persistence:
    enabled: true
    storageClass: ""
    uploadsSize: "5Gi"
    logsSize: "1Gi"

# Frontend configuration
frontend:
  image:
    repository: yourrepo/eshop-frontend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  env:
    NODE_ENV: production
    PORT: 3000
    API_URL: http://eshop-backend:3001
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  persistence:
    enabled: true
    storageClass: ""
    cacheSize: "2Gi"

# PostgreSQL configuration
postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 15-alpine
    pullPolicy: IfNotPresent
  auth:
    username: eshop
    password: eshop_password
    database: eshop
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
  service:
    port: 5432
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# Redis configuration
redis:
  enabled: true
  image:
    repository: redis
    tag: 7-alpine
    pullPolicy: IfNotPresent
  password: eshop_redis_password
  persistence:
    enabled: false
    size: 1Gi
    storageClass: ""
  service:
    port: 6379
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Nginx configuration (optional reverse proxy)
nginx:
  enabled: false
  image:
    repository: nginx
    tag: stable-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: eshop.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
          port: 3000
        - path: /api
          pathType: Prefix
          service: backend
          port: 3001
  tls: []
  #  - secretName: eshop-tls
  #    hosts:
  #      - eshop.local 